### ISSUE TITLE
Icon not appearing in toolbar

### ISSUE THREAD

**Issue by Kahran042** [Cicero-Interactive/Classic-YouTube-Design#1]
I recently downloaded this as preparation for March, but for some reason it's not showing up in my toolbar. Is this a bug or a deliberate decision?

**Comment by Cicero-Interactive** [comment]
First of all, thanks for using our extension! :) It is still in the alpha phase, so many things don't work as of now or are not implemented yet.
Currently there's no icon, because all you could do right now is toggle it on or off, which you can already do by disabling it in the add-ons page of Firefox. However, as new features are being added, we'll provide an icon with some settings.

**Comment by Kahran042** [comment]
Good to know - thanks. I currently have it deactivated, but plan to
activate in March if my other YouTube Classic extension stops working then.
Here's hoping things go well.

**Comment by NebelNidas** [comment]
Good news for you - I'm currently working on a dropdown menu where you are able to configure many of the settings the extension changes. Stay tuned!

**Comment by Kahran042** [comment]
Excellent!

**Comment by NebelNidas** [comment]
A bit late, but I released 0.2.0 preview 1 today, which contains this feature. 😉
