### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Kahran042** [Cicero-Interactive/Classic-YouTube-Design#3]
When I loaded a video, it was in classic mode, but the video didn't actually play. So I reloaded it, only for it to be in the new mode. I tried adding "?disable_polymer=true" to the URL, but that didn't work, either. Is there any other way to fix this?

**Comment by NebelNidas** [comment]
I think you are misunderstanding the extension's purpose. As stated in the description, it doesn't redirect you to the old layout (which doesn't exist anymore since a few days, hence the "?disable_polymer=true" not working), but instead 
> Recreates the classic YouTube experience within the new polymer layout.

All other classic YouTube extensions don't work anymore, because they only redirect to the now non-existent old layout. Knowing that this day would come, I created this add-on here, which tries to customize the new layout in a way that it looks like to old one.
The current implementation is far from perfect and because of collage wasn't really able to work on improvements until last week, but soon I'll release a new version which does a much better job. Stay tuned! 😉
