### ISSUE TITLE
Has Development Stopped?

### ISSUE THREAD

**Issue by DesertStars** [Cicero-Interactive/Classic-YouTube-Design#4]
I've been running into some temporary issues lately with this add-on, so I'm wondering if the development is still ongoing or not.

**Comment by Deerath** [comment]
I'd like to know the same.  I'm assuming it needs an update given that layout no longer works, and has resorted to the ugly youtube default layout.

**Comment by NebelNidas** [comment]
It's not really abandoned, I unfortunately just don't have very much time for it. Also, it doesn't help that v0.2.0 was supposed to be quite a big update, which turned out to be really time consuming. Sorry for the long wait, I'll try to split it into smaller updates and release previews with the already finished parts.

Thanks for the report with the big video titles, I didn't notice them until today, so they must've been introduced at max. a few days ago. Will fix as soon as possible!

**Comment by NebelNidas** [comment]
Just released preview 1 today, others will follow soon! However, my time is still quite limited, so if you feel like needing a specific feature sooner rather than later or just want to help out in general, feel free to contribute! 😁
